name: postgres-pgadmin


services:

    postgres:
        container_name: postgresql
        environment:
            - POSTGRES_USER=myusername
            - POSTGRES_PASSWORD=mypassword
        ports:
            - 5432:5432
        volumes:
            - /data:/var/lib/postgresql/data
        image: postgres:latest

    pgadmin4:
        container_name: my-pgadmin
        ports:
            - 8080:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=youremail@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=postgresmaster
        image: dpage/pgadmin4:latest