
name: simple-app-ex-13
services:
    simple_app:
        container_name: web
        ports:
            - 8000:8000
        volumes:
            - ./static:/app/staticfiles
        environment:
            - DEBUG=False
        build: .
