
name: Books App CI

on:
    push:
        branches: [ "main" ]

    pull_request:
        branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install npm pack & Build the program
      run: npm install

    - name: Run the application
      run: npm run start-server &

    - name: Run API tests
      run: npm run start-mocha

