
name: to-do-app-ex9

services:

  frontend:
    networks:
      - react-express
    ports:
      - 3000:3000
    build: ./frontend

  backend:
    networks:
      - react-express
      - express-mongo
    build: ./backend

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo

networks:
  express-mongo:
    name: express-mongo
  react-express:
    name: react-express