global:
  scrape_interval: 3s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
  - "alert-rules-exam.yml"

scrape_configs:
  - job_name: "blackbox"
    metrics_path: /probe
    static_configs:
      - targets:
          - https://softunibazaservice.azurewebsites.net/

    # blackbox config
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115