
name: Student Registry App CI

on:
    push:
        branches: [ "main" ]
        paths:
          - 'DevOps-and-Software-Engineering/Software Engineering and DevOps - may 2024/10-GithubActions-Exercise/01.Student-Registry-App/**'
    pull_request:
        branches: [ "main" ]
        paths:
          - 'DevOps-and-Software-Engineering/Software Engineering and DevOps - may 2024/10-GithubActions-Exercise/01.Student-Registry-App/**'
    workflow_dispatch: 

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 16.x, 18.x]
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: Install npm pack & Build the program
      working-directory: DevOps-and-Software-Engineering/Software Engineering and DevOps - may 2024/10-GithubActions-Exercise/01.Student-Registry-App
      run: npm install

    - name: Run the application
      working-directory: DevOps-and-Software-Engineering/Software Engineering and DevOps - may 2024/10-GithubActions-Exercise/01.Student-Registry-App
      run: npm start &

    - name: Run IU tests
      working-directory: DevOps-and-Software-Engineering/Software Engineering and DevOps - may 2024/10-GithubActions-Exercise/01.Student-Registry-App
      run: npm test

    - name: Run Audit tests
      working-directory: DevOps-and-Software-Engineering/Software Engineering and DevOps - may 2024/10-GithubActions-Exercise/01.Student-Registry-App
      run: npm run audit-test